import {
  siPython,
  siPostgresql,
  siRedis,
  siApachekafka,
  siDocker,
  siHelm,
  siReact,
  siTypescript,
  siJavascript,
  siVuedotjs,
  siNodedotjs,
  siMysql,
  siPhp,
  siNextdotjs,
  siGo,
  siMongodb,
  siKubernetes,
  siGithubactions,
  siRust,
  siRuby,
  siKotlin,
  siSwift,
  siDart,
  siFlutter,
  siAndroid,
  siApple,
  siLinux,
  siGit,
  siGithub,
  siGitlab,
  siBitbucket,
  siNginx,
  siApache,
  siGraphql,
  siElasticsearch,
  siRabbitmq,
  siTerraform,
  siAnsible,
  siJenkins,
  siCircleci,
  siTailwindcss,
  siCss,
  siHtml5,
  siSass,
  siWebpack,
  siVite,
  siFigma,
  siGooglecloud,
  siFirebase,
  siSupabase,
  siPrisma,
  siDjango,
  siFastapi,
  siFlask,
  siLaravel,
  siSpring,
  siSvelte,
  siAngular,
  siExpress,
  siCplusplus,
  siC,
  siSharp,
  siAstro,
  siStorybook,
  siVitest,
  siJest,
  siCypress,
  siRedux,
  siMui,
} from "simple-icons";

interface IconData {
  path: string;
  hex: string;
}

const ICON_MAP: Record<string, IconData> = {
  python:           { path: siPython.path,           hex: siPython.hex },
  postgresql:       { path: siPostgresql.path,       hex: siPostgresql.hex },
  postgres:         { path: siPostgresql.path,       hex: siPostgresql.hex },
  redis:            { path: siRedis.path,            hex: siRedis.hex },
  kafka:            { path: siApachekafka.path,      hex: siApachekafka.hex },
  "apache kafka":   { path: siApachekafka.path,      hex: siApachekafka.hex },
  docker:           { path: siDocker.path,           hex: siDocker.hex },
  helm:             { path: siHelm.path,             hex: siHelm.hex },
  react:            { path: siReact.path,            hex: siReact.hex },
  typescript:       { path: siTypescript.path,       hex: siTypescript.hex },
  javascript:       { path: siJavascript.path,       hex: siJavascript.hex },
  "vue.js":         { path: siVuedotjs.path,         hex: siVuedotjs.hex },
  vue:              { path: siVuedotjs.path,         hex: siVuedotjs.hex },
  "node.js":        { path: siNodedotjs.path,        hex: siNodedotjs.hex },
  nodejs:           { path: siNodedotjs.path,        hex: siNodedotjs.hex },
  node:             { path: siNodedotjs.path,        hex: siNodedotjs.hex },
  mysql:            { path: siMysql.path,            hex: siMysql.hex },
  php:              { path: siPhp.path,              hex: siPhp.hex },
  "next.js":        { path: siNextdotjs.path,        hex: siNextdotjs.hex },
  nextjs:           { path: siNextdotjs.path,        hex: siNextdotjs.hex },
  go:               { path: siGo.path,               hex: siGo.hex },
  golang:           { path: siGo.path,               hex: siGo.hex },
  mongodb:          { path: siMongodb.path,          hex: siMongodb.hex },
  kubernetes:       { path: siKubernetes.path,       hex: siKubernetes.hex },
  k8s:              { path: siKubernetes.path,       hex: siKubernetes.hex },
  "github actions": { path: siGithubactions.path,    hex: siGithubactions.hex },
  rust:             { path: siRust.path,             hex: siRust.hex },
  ruby:             { path: siRuby.path,             hex: siRuby.hex },
  kotlin:           { path: siKotlin.path,           hex: siKotlin.hex },
  swift:            { path: siSwift.path,            hex: siSwift.hex },
  dart:             { path: siDart.path,             hex: siDart.hex },
  flutter:          { path: siFlutter.path,          hex: siFlutter.hex },
  android:          { path: siAndroid.path,          hex: siAndroid.hex },
  ios:              { path: siApple.path,            hex: siApple.hex },
  apple:            { path: siApple.path,            hex: siApple.hex },
  linux:            { path: siLinux.path,            hex: siLinux.hex },
  git:              { path: siGit.path,              hex: siGit.hex },
  github:           { path: siGithub.path,           hex: siGithub.hex },
  gitlab:           { path: siGitlab.path,           hex: siGitlab.hex },
  bitbucket:        { path: siBitbucket.path,        hex: siBitbucket.hex },
  nginx:            { path: siNginx.path,            hex: siNginx.hex },
  apache:           { path: siApache.path,           hex: siApache.hex },
  graphql:          { path: siGraphql.path,          hex: siGraphql.hex },
  elasticsearch:    { path: siElasticsearch.path,    hex: siElasticsearch.hex },
  rabbitmq:         { path: siRabbitmq.path,         hex: siRabbitmq.hex },
  terraform:        { path: siTerraform.path,        hex: siTerraform.hex },
  ansible:          { path: siAnsible.path,          hex: siAnsible.hex },
  jenkins:          { path: siJenkins.path,          hex: siJenkins.hex },
  circleci:         { path: siCircleci.path,         hex: siCircleci.hex },
  tailwind:         { path: siTailwindcss.path,      hex: siTailwindcss.hex },
  "tailwind css":   { path: siTailwindcss.path,      hex: siTailwindcss.hex },
  css:              { path: siCss.path,              hex: siCss.hex },
  html:             { path: siHtml5.path,            hex: siHtml5.hex },
  sass:             { path: siSass.path,             hex: siSass.hex },
  webpack:          { path: siWebpack.path,          hex: siWebpack.hex },
  vite:             { path: siVite.path,             hex: siVite.hex },
  figma:            { path: siFigma.path,            hex: siFigma.hex },
  gcp:              { path: siGooglecloud.path,      hex: siGooglecloud.hex },
  "google cloud":   { path: siGooglecloud.path,      hex: siGooglecloud.hex },
  firebase:         { path: siFirebase.path,         hex: siFirebase.hex },
  supabase:         { path: siSupabase.path,         hex: siSupabase.hex },
  prisma:           { path: siPrisma.path,           hex: siPrisma.hex },
  django:           { path: siDjango.path,           hex: siDjango.hex },
  fastapi:          { path: siFastapi.path,          hex: siFastapi.hex },
  flask:            { path: siFlask.path,            hex: siFlask.hex },
  laravel:          { path: siLaravel.path,          hex: siLaravel.hex },
  spring:           { path: siSpring.path,           hex: siSpring.hex },
  svelte:           { path: siSvelte.path,           hex: siSvelte.hex },
  angular:          { path: siAngular.path,          hex: siAngular.hex },
  express:          { path: siExpress.path,          hex: siExpress.hex },
  "c++":            { path: siCplusplus.path,        hex: siCplusplus.hex },
  "c#":             { path: siSharp.path,            hex: siSharp.hex },
  csharp:           { path: siSharp.path,            hex: siSharp.hex },
  c:                { path: siC.path,                hex: siC.hex },
  astro:            { path: siAstro.path,            hex: siAstro.hex },
  storybook:        { path: siStorybook.path,        hex: siStorybook.hex },
  vitest:           { path: siVitest.path,           hex: siVitest.hex },
  jest:             { path: siJest.path,             hex: siJest.hex },
  cypress:          { path: siCypress.path,          hex: siCypress.hex },
  redux:            { path: siRedux.path,            hex: siRedux.hex },
  mui:              { path: siMui.path,              hex: siMui.hex },
};

const FALLBACK_HEX = "64748b"; // slate-500

export function getTechIcon(name: string): IconData {
  return ICON_MAP[name.toLowerCase()] ?? { path: "", hex: FALLBACK_HEX };
}
